import discord
from discord.ext import commands
import random
import os
import asyncio
import subprocess
import json
from pathlib import Path
import wget
import math
import requests
import time
import sys
import logging

client = discord.Client()
client = commands.Bot(command_prefix = '$')
#Public Class
class Fighters:
  def __init__(self, challenger, Enemy, Accept):
    self.challenger = challenger
    self.Enemy = Enemy
    self.Accept = False
@client.event
async def on_ready():
    print('We have logged in as {0.user}'.format(client))
@client.event
async def on_message(message, filename = "Players.json"):

    if message.author == client.user:
        return
    print('(', message.guild.name, ')',message.author, ':', message.content)

#test command
    if message.content.startswith('$hello'):
        await message.channel.send('Hello!')
#help
    if message.content.startswith('$help'):
        try:
            output = message.content.split(' ')[2 - 1]

        except IndexError:
            embedVar = discord.Embed(title="WearyHelp", description="If you have any questions ask megaboi#6969", color=0x00ff00)
            embedVar.add_field(name="Fun", value="$help 1", inline=False)
            embedVar.add_field(name="Math", value="$help 2", inline=False)
            await message.channel.send(embed=embedVar)
        if output == '1':
            embedVar = discord.Embed(title="WearyHelp", description="If you have any questions ask megaboi#6969", color=0x00ff00)
            embedVar.add_field(name="$randomperson", value="grabs a image of a rando from ur basement", inline=False)
            embedVar.add_field(name="$randomquote", value="grabs only the finest quotes generated by ai", inline=False)
            embedVar.add_field(name="$randomjoke", value="gives a random joke (warning some may have some nsfw lol)", inline=False)
            embedVar.add_field(name="$rickroll", value="this command will never give you up nor let you down",inline=False)
            embedVar.add_field(name="$8ball", value="Predicts the future :OOOOO",inline=False)
            embedVar.add_field(name="$rolldice", value="roll sum die", inline=False)
            embedVar.add_field(name="$action", value="commit warcrimes on another user [somewhat nsfw]", inline=False)
            await message.channel.send(embed=embedVar)
        if output == '2':
            embedVar = discord.Embed(title="WearyHelp", description="If you have any questions ask megaboi#6969", color=0x00ff00)
            embedVar.add_field(name="$add num1 num2", value="adds to the 2 numbers you've choosen for no reason :rolling_eyes:", inline=False)
            embedVar.add_field(name="what is pi", value="gives you a free slice", inline=False)
            embedVar.add_field(name="$subtract num1 num2", value="subtracts numbers", inline=False)
            embedVar.add_field(name="$multiply num1 num2", value="multiplies the amount of gfs you've had times 0",inline=False)
            embedVar.add_field(name="$divide num1 num2", value="divides stuff",inline=False)
            embedVar.add_field(name="$equation num1 +/-///*/ num2", value="all in one math command", inline=False)
            await message.channel.send(embed=embedVar)

#rickroll
    if message.content.startswith('$rickroll'):
        await message.channel.send('https://cdn.discordapp.com/attachments/786115426697478144/820413006377910282/yt1s.com_-_Rick_Astley_Never_Gonna_Give_You_Up_4K_60_FPS_Remastered_v720P.mp4')
#dmme
    if message.content.startswith('$dmme'):
        await message.author.dm_channel.send('h')
#nayfen
    if message.content.startswith('nayfen'):
        await message.channel.send('em')
#em
    if message.content.startswith('em'):
        await message.channel.send('Nayfen')
#balls
    if message.content.startswith('$balls'):
        await message.channel.send('BALLS')
#sendnudes
    if message.content.startswith('$sendnudes'):
        await message.channel.send('Nayfen :weary:')
#baka
    if message.content.startswith('$baka'):
        await message.channel.send('fuck you for using that command you dipshit')

#cheat
    if message.content.startswith('$cheat'):
        await message.channel.send('Not you cheating on me :worried:')
#watchaeating
    if message.content.startswith('$watcha eating'):
        await message.channel.send('Guys I’m eating a burger rn')
#canIhaveIt
    if message.content.startswith('$can I have it'):
        await message.channel.send('Sure Bestie')
#useggsy
    if message.content.startswith('$u seggsy'):
        await message.channel.send('no u')
#heybestie
    if message.content.startswith('$hey bestie'):
        await message.channel.send('Hey bestie!!!!')
#marioirl
    if message.content.startswith('marioirl'):
        await message.channel.send('https://cdn.discordapp.com/attachments/554704777548791829/821184817106386964/video0.mp4')
#icpoopy
    if message.content.startswith('I see poopy'):
        await message.channel.send('https://media.discordapp.net/attachments/725836813872267275/795444244088750150/poopy.gif?width=374&height=288')
    if message.content.startswith('i see poopy'):
        await message.channel.send('https://media.discordapp.net/attachments/725836813872267275/795444244088750150/poopy.gif?width=374&height=288')
#emrickroll
    if message.content.startswith('$emrickroll'):
        await message.channel.send('https://cdn.discordapp.com/attachments/783589176943312929/821806055402766376/cache211910989.mp4')
#attract
    if message.content.startswith('$attract'):
        await message.channel.send('hi! I realize this might come off as a bit odd haha.. but before the whole quarantine thing I saw you around school, and you seem really cool. If you arent interested in talking thats alright, no worries!')
#randomperson
    if message.content.startswith('$randomperson'):
        os.system('curl -o person.png https://thispersondoesnotexist.com/image')
        await message.channel.send(file=discord.File('person.png'))
#pls bully me
    if message.content.startswith('pls bully me'):
        await message.channel.send('ok daddy :weary:')
#randomquote
    if message.content.startswith('$randomquote'):
        os.system('curl https://inspirobot.me/api?generate=true --output url.txt')
        url = open('url.txt', 'r').read().replace('\n', ' ')
        print(url)
        r = requests.get(url, allow_redirects=True)

        open('quote.png', 'wb').write(r.content)
        await message.channel.send(file=discord.File('quote.png'))
#spam
    #if message.content.startswith('spam'):
        #await message.channel.send('spam')
        #await message.channel.send('spam')
        #await message.channel.send('spam')
        #await message.channel.send('spam')
        #await message.channel.send('spam')
        #await message.channel.send('spam')
        #await message.channel.send('spam')
        #await message.channel.send('spam')
        #await message.channel.send('spam')
#joke
    if '$randomjoke' in message.content:
        r = requests.get('http://v2.jokeapi.dev/joke/Any?blacklistFlags=religious,racist,sexist&format=txt', allow_redirects=True)

        open('joke.txt', 'wb').write(r.content)
        joke = open('joke.txt', 'r').read().replace('\n', ' ')
        await message.channel.send(joke)
#test
    if message.content.startswith('!hello'):
        await message.channel.send("content", file=discord.File('help2.png'))

#test
    if message.content.startswith('$bingo'):
        await message.channel.send('bingo')
        await message.channel.send('- colton')
#randomnumber
    if message.content.startswith('$rolldice'):

        numbers = ["1", "2", "3", "4", "5", "6"]
        picked = random.choice(numbers)
        await message.channel.send('you rolled and got a '+ picked)
#8ball
    if message.content.startswith('$8ball'):
        outcomes = ["As I see it, yes.", "Ask again later.", "Better not tell you now.", "Cannot predict now.", "Concentrate and ask again.", "Don’t count on it.", "It is certain.", "It is decidedly so.", "Most likely.", "My reply is no.", "My sources say no.", "Outlook not so good.", "Outlook good.", "Reply hazy, try again.","Signs point to yes.", "Very doubtful.", "Without a doubt.", "Yes.", "Yes – definitely.", "You may rely on it."]

        picked2 = random.choice(outcomes)
        await message.channel.send(picked2)
#yes
    if message.content.startswith('what is pi'):
        await message.channel.send(math.pi)
#whoami
    if message.content.startswith('who am I'):
        await message.channel.send(message.author)
#enn word :ban:
#forgive me mother for the swear
    if 'nigg' in message.content:
        await message.channel.send('HEY!!! NO Enn WORD >:((((( ')
        await message.channel.send(message.author)
        await message.delete()
        print('warned', message.author)
    if 'Nigg' in message.content:
        await message.channel.send('HEY!!! NO Enn WORD >:((((( ')
        await message.channel.send(message.author)
        await message.delete()
        print('warned', message.author)
#shutdown
    if message.content.startswith('$shutdown'):
        await message.channel.send('shutting down in 10 second(s)')
        time.sleep(1)
        await message.channel.send('shutting down in 9 second(s)')
        time.sleep(1)
        await message.channel.send('shutting down in 8 second(s)')
        time.sleep(1)
        await message.channel.send('shutting down in 7 second(s)')
        time.sleep(1)
        await message.channel.send('shutting down in 6 second(s)')
        time.sleep(1)
        await message.channel.send('shutting down in 5 second(s)')
        time.sleep(1)
        await message.channel.send('shutting down in 4 second(s)')
        time.sleep(1)
        await message.channel.send('shutting down in 3 second(s)')
        time.sleep(1)
        await message.channel.send('shutting down in 2 second(s)')
        time.sleep(1)
        await message.channel.send('shutting down in 1 second(s)')
        time.sleep(1)
        await message.channel.send('lol jk')
#args test
    if message.content.startswith('$echo'):
        output = message.content.replace('$echo', '')
        try:
            if output == '':
                await message.channel.send('invalid characters or blank spaces')
            else:
                await message.channel.send(output)
        except discord.errors.HTTPException:
            await message.channel.send('invalid characters or blank spaces')


#add
    if message.content.startswith('$add'):
        try:
            output = message.content.split(' ')[2 - 1]
            output2 = message.content.split(' ')[3 - 1]
        except IndexError:
            await message.channel.send('Syntax error - $add num1 num2')
            return
        except UnboundLocalError:
            return
        try:
            output3 = int(output) + int(output2)
        except ValueError:
            await message.channel.send('bruh those are letters :joy:')
            return
        await message.channel.send(output3)
#subtract
    if message.content.startswith('$subtract'):
        try:
            output = message.content.split(' ')[2 - 1]
            output2 = message.content.split(' ')[3 - 1]
        except IndexError:
            await message.channel.send('Syntax error - $subtract num1 num2')
            return
        except UnboundLocalError:
            return
        try:
            output3 = int(output) - int(output2)
        except ValueError:
            await message.channel.send('bruh those are letters :joy:')
            return
        await message.channel.send(output3)
#divide
    if message.content.startswith('$divide'):
        try:
            output = message.content.split(' ')[2 - 1]
            output2 = message.content.split(' ')[3 - 1]
        except IndexError:
            await message.channel.send('Syntax error - $divide num1 num2')
            return
        except UnboundLocalError:
            return
        try:
            output3 = int(output) / int(output2)
        except ValueError:
            await message.channel.send('bruh those are letters :joy:')
            return
        await message.channel.send(output3)
#multiply
    if message.content.startswith('$multiply'):
        try:
            output = message.content.split(' ')[2 - 1]
            output2 = message.content.split(' ')[3 - 1]
        except IndexError:
            await message.channel.send('Syntax error - $multiply num1 num2')
            return
        except UnboundLocalError:
            return
        try:
            output3 = int(output) * int(output2)
        except ValueError:
            await message.channel.send('bruh those are letters :joy:')
            return
        await message.channel.send(output3)
#minecraft
    if message.content.startswith('$skin'):
        output = message.content.split(' ')[2 - 1]
        await message.channel.send('https://minotar.net/armor/body/' + output + '/100.png')
#equation
    if message.content.startswith('$equation'):
        output = message.content.split(' ')[2 - 1]
        output2 = message.content.split(' ')[3 - 1]
        output3 = message.content.split(' ')[4 - 1]
        try:
            if output2 == '+':
                try:
                    output = message.content.split(' ')[2 - 1]
                    output2 = message.content.split(' ')[4 - 1]
                except IndexError:
                    await message.channel.send('Syntax error - $equation num1 + num2')
                    return
                except UnboundLocalError:
                    return
                try:
                    output3 = int(output) + int(output2)
                except ValueError:
                    await message.channel.send('bruh those are letters :joy:')
                    return
                await message.channel.send(output3)
            if output2 == '-':
                    try:
                        output = message.content.split(' ')[2 - 1]
                        output2 = message.content.split(' ')[4 - 1]
                    except IndexError:
                        await message.channel.send('Syntax error - $subtract num1 - num2')
                        return
                    except UnboundLocalError:
                        return
                    try:
                        output3 = int(output) - int(output2)
                    except ValueError:
                        await message.channel.send('bruh those are letters :joy:')
                        return
                    await message.channel.send(output3)
            if output2 == '/':
                    try:
                        output = message.content.split(' ')[2 - 1]
                        output2 = message.content.split(' ')[4 - 1]
                    except IndexError:
                        await message.channel.send('Syntax error - $divide num1 / num2')
                        return
                    except UnboundLocalError:
                        return
                    try:
                        output3 = int(output) / int(output2)
                    except ValueError:
                        await message.channel.send('bruh those are letters :joy:')
                        return
                    await message.channel.send(output3)
            if output2 =='*':
                try:
                    output = message.content.split(' ')[2 - 1]
                    output2 = message.content.split(' ')[3 - 1]
                except IndexError:
                    await message.channel.send('Syntax error - $multiply num1 num2')
                    return
                except UnboundLocalError:
                    return
                try:
                    output3 = int(output) * int(output2)
                except ValueError:
                    await message.channel.send('bruh those are letters :joy:')
                    return
                await message.channel.send(output3)
        except IndexError:
            await message.channel.send('Syntax error - $equation num1 +/-/*/ / / num2')
#action
    if message.content.startswith('$action'):
        output = message.content.replace('$action', '')
        action = ["Kicked","Killed","Punched","Ticked","Scratched","Licked","ran from","bullied","sat on","threw lima beans at","cried about","gulped down a cow in front of","murdered","Grappled onto","saw and ran to","kissed","skinned","ate","almost did it with","yanked","walked into","saw","twisted","pulverized","sucked all the bone marrow out of","wrote on","skipped over","jumped on","reverantly touched","stepped on","brushed","gave Covid-19 to","hushed","reached lower on","rejected","proposed","traded there life to","spat rice out onto","threw yellow pigs at","traded his money for spoons to","sat onto","threw clothes","is in love with"]
        action2 = random.choice(action)
        if output == '':
            await message.channel.send('bruh theres no word smh')
            return
        if output == message.author.mention:
            await message.channel.send('you cannot perform an action on yourself')
            return
        await message.channel.send(message.author.mention +' ' + action2 + output)
#FIGHTBOT CODE
    ############
    # FUNCTIONS
    ############

    # Function to add player to player database
    def add_player(user=message.author, filename="Players.json"):
        with open(filename, 'r') as f:
            users = json.load(f)

        whoWins = (f"{message.author.mention}Wins")
        whoLoses = (f"{message.author.mention}Losses")

        if whoWins in users and whoLoses in users:
            return False;

        else:
            users[whoWins] = 0
            users[whoLoses] = 0

        with open(filename, 'w') as f:
            json.dump(users, f)

    # updates the player's win/loss
    def update_player(user):
        add_player()
        with open(filename, 'r') as f:
            users = json.load(f)

        with open(filename, "w") as f:
            json.dump(users, f)

        users[user] += 1

        with open(filename, "w") as f:
            json.dump(users, f)

    # fight function
    async def FuncFight():
        RandomWeapon = ["sword", "rock", "tomato", "finger", "grass", "computer", "cup", "steak", "dishwasher",
                        "bouncy ball", "tooth", "sledgehammer"]
        RandomSenario = ["mauled", "stabbed", "scratched", "punched", "petted", "licked", "scratched", "thrown",
                         "slapped", "slapped", "uwu'd", "anime'd"]
        RandomWinner = [Fighters.challenger, message.author]

        WeaponChooser = random.choice(RandomWeapon)
        SenarioChooser = random.choice(RandomSenario)
        WinnerChooser = random.choice(RandomWinner)

        if WinnerChooser == Fighters.challenger:
            await message.channel.send(
                f"{message.author.mention} was {SenarioChooser} with a {WeaponChooser} by {Fighters.challenger}")

            update_player(f"{Fighters.challenger}Losses")
            update_player(f"{message.author.mention}Wins")
        else:
            await message.channel.send(
                f"{Fighters.challenger} was {SenarioChooser} with a {WeaponChooser} by {message.author.mention}")

            update_player(f"{message.author.mention}Wins")
            update_player(f"{Fighters.challenger}Losses")

    # Timer function. A sort of fight deny before I actually add the commands. It also counts as a time limit. Raise from 15?
    async def FuncTimer(t=0):

        while t <= 15:
            await asyncio.sleep(1)
            t += 1

        if t > 15:
            if Fighters.Accept == True:
                t = 0
                Fighters.Accept = False
                Fighters.challenger = "None"
                Fighters.Enemy = "None"
                Fighters.Accept = False
                t = 0
            else:
                await message.channel.send(
                    f"{message.author.mention} Your enemy was either too late to accept, or they were a coward. Shame!")
                Fighters.challenger = "None"
                Fighters.Enemy = "None"
                Fighters.Accept = False
                t = 0

    ##############
    # COMMANDS
    #############

    # profile command
    if message.content.startswith('$fipr'):
        add_player()
        user = message.author.mention

        with open(filename, 'r') as f:
            users = json.load(f)

        with open(filename, "w") as f:
            json.dump(users, f)

        win_amount = users[f"{user}Wins"]
        loss_amount = users[f"{user}Losses"]

        em = discord.Embed(title=f"{message.author}'s wins", color=discord.Color.green())
        em.add_field(name="wins", value=win_amount)
        em.add_field(name="losses", value=loss_amount)
        await message.channel.send(embed=em)

    # Fight request
    if message.content.startswith("$fight"):
        add_player()
        user = message.author

        Contents = message.content.replace('$fight ', '')
        if message.author.mention != Contents:
            if '@' in message.content:
                request = True

                Fighters.challenger = message.author.mention
                Fighters.Enemy = Contents

                await message.channel.send(
                    f"{Contents} was challenged to a duel by {message.author.mention}! Do $faccept {message.author.mention} if you accept!")
                Fighters.Accept = False
                await FuncTimer()

            else:
                await message.channel.send("You can't just fight a imaginary friend you crank!")
        else:
            await message.channel.send("You can't fight yourself you crazy bastard")

    # Accept Command
    if message.content.startswith('$faccept'):

        add_player()
        input = message.content.replace('$faccept ', '')

        if message.author.mention == Fighters.Enemy:

            if Fighters.challenger != message.content:

                await message.channel.send(
                    f"{message.author.mention} has accepted the duel from {Fighters.challenger}!")
                Fighters.Accept = True
                await FuncFight();


            else:
                await message.channel.send(
                    "You have requested to accept from the wrong person, or no one has requested to fight you")
        else:
            await message.channel.send("No one challenged YOU silly")


#end of fightbot








#async def on_ready():
    #await client.change_presence(activity=discord.Game('Dead by daylight'))

    #print('Connected to bot: {}'.format(client.user.name))
    #print('Bot ID: {}'.format(client.user.id))

async def ch_pr():
    await client.wait_until_ready()

    statuses = ["BALLS","Minecraft","and streaming seggsy girl plays dbd"]

    while not client.is_closed():

        status = random.choice(statuses)
        await client.change_presence(activity=discord.Game(name=status,))

        await asyncio.sleep(5)
client.loop.create_task(ch_pr())
#yes
client.run('token')